---
- name: Migration compatibility check - src
  hosts: all
  gather_facts: no
  tasks:
    - name: set index variable
      set_fact:
        index: "{{ groups['all'].index(inventory_hostname) }}"

    - name: Initialize contaier
      shell: /home/ec2-user/migration_test/podman_init.sh -a
      become: true
      ignore_errors: yes

    - name: Initialize source instance
      shell: |
        mkdir /home/ec2-user/migration_test/dump/{{ index }}

    - name: logging - write the src instance type
      shell: |
        echo "src : $(curl http://169.254.169.254/latest/meta-data/instance-type)" > /home/ec2-user/migration_test/dump/{{ index }}/performance.log

    - name: Create container
      shell: /home/ec2-user/migration_test/create_container.sh -u
      become: true

    - name: wait for 5 sec
      wait_for:
        timeout: 5
      register: result

    - name: logging - write the checkpoint start time
      shell: |
        echo start checkpoint : $(date) >> /home/ec2-user/migration_test/dump/{{ index }}/timestamp.log

    - name: Container checkpoint
      shell: /home/ec2-user/migration_test/checkpoint.sh -n {{ index }}
      become: true

    - name: logging - write the checkpoint end time
      shell: |
        echo end checkpoint : $(date) >> /home/ec2-user/migration_test/dump/{{ index }}/timestamp.log