---
- name: Migration compatibility check - src
  hosts: all
  gather_facts: no
  tasks:
    - name: set index variable
      set_fact:
        index: "{{ groups['all'].index(inventory_hostname) }}"  

    - name: Initialize source instance
      shell: |
        mkdir /home/ubuntu/migration_test/dump/{{ index }}

    - name: Increase PID
      shell: |
        python3 /home/ubuntu/migration_test/increase_pid.py > /dev/null

    - name: Start workload
      shell: |
        export LD_BIND_NOW=1; \
        nohup /home/ubuntu/anaconda3/condabin/conda run -n rubin-sim python3 /home/ubuntu/migration_test/rubin_sim_notebooks/maf/science/AGN_N_qsos.py 1>/dev/null 2>&1 &

    - name: logging - write the src instance type
      shell: |
        echo "src : $(curl http://169.254.169.254/latest/meta-data/instance-type)" > /home/ubuntu/migration_test/dump/{{ index }}/performance.log

    - name: Get workload PID
      shell: pgrep -f AGN_N_qsos.py
      register: PID

    - name: logging - write the checkpoint start time
      shell: |
        echo start checkpoint : $(date +'%Y-%m-%dT%H:%M:%S') > /home/ubuntu/migration_test/dump/{{ index }}/timestamp.log

    - name: Checkpoint workload
      shell: |
        sudo criu dump -j -v4 --display-stats -D /home/ubuntu/migration_test/dump/{{ index }}/ -t {{ PID.stdout_lines[0] }} >> /home/ubuntu/migration_test/dump/{{ index }}/performance.log \
        2> /home/ubuntu/migration_test/"$(sed -n '/src :/s/^src : //p' /home/ubuntu/migration_test/dump/{{ index }}/performance.log)-dump.log"

    - name: Wait for *-dump.log to be created
      ansible.builtin.find:
        paths: "/home/ubuntu/migration_test"
        patterns: '*-dump.log'
      register: found_files
      until: found_files.matched > 0
      retries: 3
      delay: 10

    - name: Check for success message in dump.log
      shell: grep -E "Dumping finished successfully" /home/ubuntu/migration_test/*-dump.log
      register: grep_result
      ignore_errors: yes
      until: grep_result.rc == 0
      retries: 18
      delay: 10

    - name: logging - write the checkpoint end time
      shell: |
        echo end checkpoint : $(date +'%Y-%m-%dT%H:%M:%S') >> /home/ubuntu/migration_test/dump/{{ index }}/timestamp.log

    - name: Upload to S3 - dump detail log
      shell: |
        aws s3 cp /home/ubuntu/migration_test/*-dump.log s3://migration-compatibility-detail