---
- name: Migration compatibility check - src
  hosts: all
  gather_facts: no
  tasks:
    - name: init
      shell: |
        sudo rm -rf /home/ubuntu/migration_test/ins_disas/log/*.csv
      ignore_errors: yes

    - name: Start workload
      shell: |
        export LD_LIBRARY_PATH=/home/ubuntu/openssl-openssl-3.1.3:$LD_LIBRARY_PATH; \
        nohup /home/ubuntu/migration_test/sha_scripts/sha > /dev/null 2>&1 &

    - name: Get workload PID
      shell: pidof sha
      register: PID

    - name: func tracking
      shell: |
        sudo /home/ubuntu/migration_test/ins_disas/measure_overhead_func_tracking.sh {{ PID.stdout_lines[0] }}

    - name: renaming log
      shell: |
        mv /home/ubuntu/migration_test/ins_disas/log/isa_set.csv /home/ubuntu/migration_test/ins_disas/log/"$(curl http://169.254.169.254/latest/meta-data/instance-type).csv"

    - name: Upload to S3 - func tracking result
      shell: |
        aws s3 cp /home/ubuntu/migration_test/ins_disas/log/*.csv s3://migration-compatibility/func-tracking-lazybinding/sha/
        