---
- name: entire scanning
  hosts: all
  gather_facts: no
  tasks:
    - name: Start workload
      shell: |
        export LD_BIND_NOW=1; \
        nohup bash -c 'cd /home/ubuntu/LiveMigrate-Detector/workload_instruction_analyzer/bytecode_tracking/exp_workloads/pku/ && python3 pku.py > /dev/null 2>&1 &'

    - name: Get workload PID
      shell: ps aux | grep "python3 pku.py" | grep -v "bash -c" | grep -v grep | awk '{print $2}'
      register: PID

    - name: entire scanning
      shell: |
        sudo /home/ubuntu/LiveMigrate-Detector/workload_instruction_analyzer/text_segment_full_scan.sh {{ PID.stdout_lines[0] }} 

    - name: renaming log
      shell: |
        mv /home/ubuntu/LiveMigrate-Detector/workload_instruction_analyzer/log/isa_set.csv /home/ubuntu/LiveMigrate-Detector/workload_instruction_analyzer/log/"$(curl http://169.254.169.254/latest/meta-data/instance-type).csv"

    - name: Upload to S3 - entire scanning result
      shell: |
        aws s3 cp /home/ubuntu/LiveMigrate-Detector/workload_instruction_analyzer/log/*.csv s3://migration-compatibility/entire-scanning/pypku/

    - name: clean-up process
      shell: |
        sudo rm -rf /home/ubuntu/LiveMigrate-Detector/workload_instruction_analyzer/log/*.csv; \
        sudo rm -rf /home/ubuntu/LiveMigrate-Detector/workload_instruction_analyzer/log/*.txt; \
        kill -9 {{ PID.stdout_lines[0] }}
      ignore_errors: yes