---
- name : Migration compatibility check - dst
  hosts: all
  gather_facts: no
  tasks:
    - name: Copy the log from the dump directory
      shell: |
        cp /home/ubuntu/migration_test/dump/{{ src }}/*.log /home/ubuntu/migration_test

    - name: logging - write the dst instance type
      shell: |
        INSTANCE_TYPE=$(curl http://169.254.169.254/latest/meta-data/instance-type) && \
        sed -i "2i dst : $INSTANCE_TYPE" /home/ubuntu/migration_test/performance.log

    - name: Get workload PID
      register: PID
      shell: |
        export PATH=$PATH:~/criu/crit/
        crit show /home/ubuntu/migration_test/dump/{{ src }}/pstree.img | jq '.entries[0].pid'

    - name: logging - process ids
      shell: |
        ps -eLf | awk '{ if ($4 != "LWP") print $4 }' > /home/ubuntu/migration_test/dst-pids.log

    - name: Upload to S3 - PID logs
      shell: |
        src_file=$(sed -n '/src :/s/^src : //p' /home/ubuntu/migration_test/performance.log)
        dst_file=$(sed -n '/dst :/s/^dst : //p' /home/ubuntu/migration_test/performance.log)
        echo "src" > "/home/ubuntu/migration_test/${src_file}_to_${dst_file}-pids.log"
        cat /home/ubuntu/migration_test/src-pids.log >> "/home/ubuntu/migration_test/${src_file}_to_${dst_file}-pids.log"
        echo "dst" >> "/home/ubuntu/migration_test/${src_file}_to_${dst_file}-pids.log"
        cat /home/ubuntu/migration_test/dst-pids.log >> "/home/ubuntu/migration_test/${src_file}_to_${dst_file}-pids.log"
        aws s3 cp "/home/ubuntu/migration_test/${src_file}_to_${dst_file}-pids.log" s3://migration-compatibility-detail

    - name: Restore workload
      shell: |
        sudo dmesg -C
        nohup sudo criu restore -j -v4 --display-stats -D /home/ubuntu/migration_test/dump/{{ src }} >> /home/ubuntu/migration_test/performance.log \
        2>> /home/ubuntu/migration_test/"$(sed -n '/src :/s/^src : //p' /home/ubuntu/migration_test/performance.log)_to_$(sed -n '/dst :/s/^dst : //p' /home/ubuntu/migration_test/performance.log)-restore.log" &

    - name: wait for 5 sec
      wait_for:
        timeout: 5
      register: result

    - name: Restore workload to stop state
      shell: |
        nohup sudo criu restore -j -s -D /home/ubuntu/migration_test/dump/{{ src }} &

    - name: process debug
      shell: |
        nohup sudo gdb python -ex "attach {{ PID.stdout_lines[0] }}" -ex "source /home/ubuntu/migration_test/gdb_script.py" &

    - name: wait for 5 sec
      wait_for:
        timeout: 5
      register: result

    - name: renaming csv
      shell: |
        mv /home/ubuntu/migration_test/output.csv /home/ubuntu/migration_test/"$(sed -n '/src :/s/^src : //p' /home/ubuntu/migration_test/performance.log)_to_$(sed -n '/dst :/s/^dst : //p' /home/ubuntu/migration_test/performance.log)-debug.csv"

    - name: Upload to S3 - debug result
      shell: |
        aws s3 cp /home/ubuntu/migration_test/*.csv s3://migration-compatibility/Migration-failure-groups/

    - name: Upload to S3 - restore detail log
      shell: |
        aws s3 cp /home/ubuntu/migration_test/*-restore.log s3://migration-compatibility-detail