---
- name: Migration compatibility check
  hosts: src
  tasks:
    - name: Initialize contaier
      shell: /home/ec2-user/podman/podman_init.sh -a
      ignore_errors: yes

    - name: Create container
      shell: /home/ec2-user/podman/create_container.sh -t

    - name: Execute workload
      shell: /home/ec2-user/podman/execute_workload_in_container.sh

    - name: wait for 5 sec
      wait_for:
        timeout: 5
      register: result

    - name: Container checkpoint
      shell: /home/ec2-user/podman/checkpoint.sh -n
      when: result.elapsed >= 5
  
- name : test
  hosts: dst
  tasks:
    - name: Initialize contaier
      shell: /home/ec2-user/podman/podman_init.sh -o
      ignore_errors: yes

    - name: Container restore
      shell: /home/ec2-user/podman/restore.sh -n
    
    - name: Crash check 
      shell: sudo podman ps -a | grep Exited
      register: container_output
      ignore_errors: yes

    - name: Combine performance and workload excute log
      shell: sudo podman cp jupynb:/home/jovyan/workload.log . ; cat workload.log >> /home/ec2-user/podman/log/performance.log
      register: result
      until: "'No such file or directory' not in result.stderr"
      retries: 30
      delay: 5
      when: container_output.stdout_lines | length == 0 # Container not crashed